export const monsterMap = [
  { id: 1, name: 'Aptonoth', path: 'MHW_Aptonoth_Icon.png' },
  { id: 2, name: 'Jagras', path: 'MHW_Jagras_Icon.png' },
  { id: 3, name: 'Mernos', path: 'MHW_Mernos_Icon.png' },
  { id: 4, name: 'Vespoid', path: 'MHW_Vespoid_Icon.png' },
  { id: 5, name: 'Mosswine', path: 'MHW_Mosswine_Icon.png' },
  { id: 6, name: 'Apceros', path: 'MHW_Apceros_Icon.png' },
  { id: 7, name: 'Kestodon', path: 'MHW_Kestodon_Icon.png' },
  { id: 8, name: 'Noios', path: 'MHW_Noios_Icon.png' },
  { id: 9, name: 'Gajau', path: 'MHW_Gajau_Icon.png' },
  { id: 10, name: 'Kelbi', path: 'MHW_Kelbi_Icon.png' },
  { id: 11, name: 'Raphinos', path: 'MHW_Raphinos_Icon.png' },
  { id: 12, name: 'Shamos', path: 'MHW_Shamos_Icon.png' },
  { id: 13, name: 'Girros', path: 'MHW_Girros_Icon.png' },
  { id: 14, name: 'Hornetaur', path: 'MHW_Hornetaur_Icon.png' },
  { id: 15, name: 'Gastodon', path: 'MHW_Gastodon_Icon.png' },
  { id: 16, name: 'Barnos', path: 'MHW_Barnos_Icon.png' },
  { id: 17, name: 'Great Jagras', path: 'MHW_Great_Jagras_Icon.png' },
  { id: 18, name: 'Kulu-Ya-Ku', path: 'MHW_Kulu-Ya-Ku_Icon.png' },
  { id: 19, name: 'Pukei-Pukei', path: 'MHW_Pukei-Pukei_Icon.png' },
  { id: 20, name: 'Barroth', path: 'MHW_Barroth_Icon.png' },
  { id: 21, name: 'Jyuratodus', path: 'MHW_Jyuratodus_Icon.png' },
  { id: 22, name: 'Tobi-Kadachi', path: 'MHW_Tobi-Kadachi_Icon.png' },
  { id: 23, name: 'Anjanath', path: 'MHW_Anjanath_Icon.png' },
  { id: 24, name: 'Azure Rathalos', path: 'MHW_Azure_Rathalos_Icon.png' },
  { id: 25, name: 'Bazelgeuse', path: 'MHW_Bazelgeuse_Icon.png' },
  { id: 26, name: 'Behemoth', path: 'MHW_Behemoth_Icon.png' },
  { id: 27, name: 'Deviljho', path: 'MHW_Deviljho_Icon.png' },
  { id: 28, name: 'Diablos', path: 'MHW_Diablos_Icon.png' },
  { id: 29, name: 'Black Diablos', path: 'MHW_Black_Diablos_Icon.png' },
  { id: 30, name: 'Dodogama', path: 'MHW_Dodogama_Icon.png' },
  { id: 31, name: 'Great Girros', path: 'MHW_Great_Girros_Icon.png' },
  { id: 32, name: 'Kirin', path: 'MHW_Kirin_Icon.png' },
  { id: 33, name: 'Kulve Taroth', path: 'MHW_Kulve_Taroth_Icon.png' },
  { id: 34, name: 'Kushala Daora', path: 'MHW_Kushala_Daora_Icon.png' },
  { id: 35, name: 'Lavasioth', path: 'MHW_Lavasioth_Icon.png' },
  { id: 36, name: 'Legiana', path: 'MHW_Legiana_Icon.png' },
  { id: 37, name: 'Lunastra', path: 'MHW_Lunastra_Icon.png' },
  { id: 38, name: 'Nergigante', path: 'MHW_Nergigante_Icon.png' },
  { id: 39, name: 'Odogaron', path: 'MHW_Odogaron_Icon.png' },
  { id: 40, name: 'Paolumu', path: 'MHW_Paolumu_Icon.png' },
  { id: 41, name: 'Radobaan', path: 'MHW_Radobaan_Icon.png' },
  { id: 42, name: 'Rathalos', path: 'MHW_Rathalos_Icon.png' },
  { id: 43, name: 'Rathian', path: 'MHW_Rathian_Icon.png' },
  { id: 44, name: 'Pink Rathian', path: 'MHW_Pink_Rathian_Icon.png' },
  { id: 45, name: 'Teostra', path: 'MHW_Teostra_Icon.png' },
  { id: 48, name: 'Tzitzi-Ya-Ku', path: 'MHW_Tzitzi-Ya-Ku_Icon.png' },
  { id: 49, name: 'Uragaan', path: 'MHW_Uragaan_Icon.png' },
  { id: 50, name: 'Vaal Hazak', path: 'MHW_Vaal_Hazak_Icon.png' },
  { id: 51, name: "Xeno'jiiva", path: "MHW_Xeno'jiiva_Icon.png" },
  { id: 52, name: 'Zorah Magdaros', path: 'MHW_Zorah_Magdaros_Icon.png' },
  { id: 53, name: 'Leshen', path: 'MHW_Leshen_Icon.png' },
  { id: 54, name: 'Ancient Leshen', path: 'MHW_Ancient_Leshen_Icon.png' },
  { id: 55, name: "Safi'jiiva", path: "MHW_Xeno'jiiva_Icon.png" },
  { id: 56, name: 'Stygian Zinogre', path: 'MHWI_Zinogre_Icon.png' },
  { id: 57, name: 'Rajang', path: 'MHWI_Rajang_Icon.png' },
  {
    id: 58,
    name: 'Viper Tobi-Kadachi',
    path: 'MHWI_Viper_Tobi-Kadachi_Icon.png'
  },
  { id: 59, name: 'Namielle', path: 'MHWI_Namielle_Icon.png' },
  { id: 60, name: 'Zinogre', path: 'MHWI_Zinogre_Icon.png' }
]
